# Creación de columnas analíticas

##### Georreferenciación, menores de edad, diversidad regional, correspondencia con rutas migratorias históricas, presencia de infraestructura de detención en municipios destino

### Georreferenciación

##### Esta sección fue realizada principalmente por @jdanielgoh

In [407]:
import geopandas as gpd
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
%pip install pyarrow

Requirement already satisfied: pyarrow in /opt/anaconda3/lib/python3.13/site-packages (19.0.0)
Note: you may need to restart the kernel to use updated packages.

In [408]:
from pathlib import Path

DATOS = Path("..") / "datos"
REFERENCIAS = DATOS / "referencias"

In [409]:
datos = pd.read_parquet(DATOS / "procesados" / "datos_limpios_concatenados.parquet")

In [410]:
catalogo_municipal = pd.read_csv(REFERENCIAS / "áreas_geoestadísticas_municipales.csv",encoding="latin-1",skiprows=2)

In [411]:
municipios = gpd.read_file(REFERENCIAS / "municipios" / "00mun.shp")

municipios = municipios.to_crs(epsg=4326)

In [412]:
catalogo_municipal["mun"] = catalogo_municipal.apply(lambda x : x["Nombre del Municipio"] + ", " + x["Nombre del Estado"] ,axis=1)
catalogo_municipal["cve_mun"] = catalogo_municipal.apply(lambda x : str(x["Clave Geoestadística Estatal"]).zfill(2) + str(x["Clave Geoestadística Municipal"]).zfill(3) ,axis=1)
diccionario_nom_cve = catalogo_municipal.set_index("mun").cve_mun.to_dict()

diccionario_cve_geom = municipios.set_index("CVEGEO").geometry.to_dict()

In [413]:
diccionario_nombres_oficiales = {'Michoacán':'Michoacán de Ocampo',
       "Veracruz":'Veracruz de Ignacio de la Llave',"Estado de México":"México"}

def limpiadoraLugares(txt):
  txt = txt.replace("El Ceibo","Tenosique")
  txt = txt.replace("Ciudad Victoria","Victoria")

  if(txt=="Ciudad del Carmen, Campeche"):
    txt = "Carmen, Campeche"
  if(txt=="Ciudad Juárez, Chihuahua"):
    txt = "Juárez, Chihuahua"
  if(txt=="Ciudad Cuauhtémoc, Chihuahua"):
    txt = "Cuauhtémoc, Chihuahua"
  if(txt=="Acapulco, Guerrero"):
    txt = "Acapulco de Juárez, Guerrero"

  if(txt=="Tlalnepantla, Estado de México"):
    txt = "Tlalnepantla de Baz, Estado de México"

  if(txt=="Talismán, Chiapas"):
    txt = "Tuxtla Chico, Chiapas"
  if(txt=="Pachuca de Soto, Hidalgo"):
    txt = "Pachuca de Soto, Hidalgo"
  if(txt=="El Carmen, Chiapas"):
    txt="Pijijiapan, Chiapas"
  if(txt=="Plan de Guadalupe, Nuevo León"):
    txt="Guadalupe, Nuevo León"
  if(txt=="Echegaray, Chiapas"):
    txt="Pijijiapan, Chiapas"
  if(txt=="Piedras Negras, Coahuila"):
    txt="Piedras Negras, Coahuila de Zaragoza"
  if(txt=="Saltillo, Coahuila"):
    txt="Saltillo, Coahuila de Zaragoza"
  if(txt=="Escuinapa de Hidalgo, Sinaloa"):
    txt="Escuinapa, Sinaloa"
  if(txt=='Guadalupe, Nuevo León  '):
    txt='Guadalupe, Nuevo León'
      
  txt_sep = txt.split(", ")
  if(txt_sep[-1] in diccionario_nombres_oficiales.keys()):
    txt_sep[-1]  = diccionario_nombres_oficiales[txt_sep[-1]]
  return ", ".join(txt_sep)

datos["origen_limpio_mun"] = datos.lugar_origen.apply(limpiadoraLugares).apply(lambda x : x.split(", ")[0])
datos["origen_limpio_ent"] = datos.lugar_origen.apply(limpiadoraLugares).apply(lambda x : x.split(", ")[-1])
datos["destino_limpio_mun"] = datos.lugar_destino.apply(limpiadoraLugares).apply(lambda x : x.split(", ")[0])
datos["destino_limpio_ent"] = datos.lugar_destino.apply(limpiadoraLugares).apply(lambda x : x.split(", ")[-1])

datos["destino_cve"] = datos.lugar_destino.apply(limpiadoraLugares).map(diccionario_nom_cve)

datos["origen_cve"] = datos.lugar_origen.apply(limpiadoraLugares).map(diccionario_nom_cve)

In [414]:
datos[datos.origen_cve.isna()].lugar_origen.value_counts()

Series([], Name: count, dtype: int64)

In [415]:
datos[datos.destino_cve.isna()].lugar_destino.value_counts()

lugar_destino
Honduras          1039
Guatemala          991
El Salvador         21
Deportación          2
Estados Unidos       2
Belice               1
Nicaragua            1
Name: count, dtype: int64

In [416]:
datos["geom_destino"] = datos.destino_cve.map(diccionario_cve_geom).apply(lambda x : x.centroid if type(x)!=float else np.nan)
datos["geom_origen"] = datos.origen_cve.map(diccionario_cve_geom).apply(lambda x : x.centroid if type(x)!=float else np.nan)

In [417]:
datos["lon_destino"] = datos["geom_destino"].apply(lambda x : x.x if type(x)!=float else np.nan )
datos["lat_destino"] = datos["geom_destino"].apply(lambda x : x.y if type(x)!=float else np.nan )

datos["lon_origen"] = datos["geom_origen"].apply(lambda x : x.x if type(x)!=float else np.nan )
datos["lat_origen"] = datos["geom_origen"].apply(lambda x : x.y if type(x)!=float else np.nan )

In [418]:
datos[["lon_origen","lat_origen"]].groupby(["lon_origen","lat_origen"]).size().reset_index().rename({0:"cant"},axis=1)

    lon_origen  lat_origen  cant
0  -116.847384   32.412116   200
1  -111.473211   29.024027   507
2  -109.162235   25.935276     4
3  -108.549129   25.518076     3
4  -108.450224   30.849353   239
..         ...         ...   ...
72  -90.474350   18.550598    23
73  -90.266050   19.616416     6
74  -89.639925   20.980519    22
75  -88.466935   18.508613    54
76  -86.940930   21.078221     6

[77 rows x 3 columns]

In [419]:
datos[["lon_origen","lat_origen","lon_destino","lat_destino"]].groupby(["lon_origen","lat_origen","lon_destino","lat_destino"]).size().reset_index().rename({0:"cant"},axis=1)

     lon_origen  lat_origen  lon_destino  lat_destino  cant
0   -116.847384   32.412116  -116.847384    32.412116     1
1   -116.847384   32.412116  -111.473211    29.024027     8
2   -116.847384   32.412116  -106.306029    23.468303     7
3   -116.847384   32.412116  -102.678068    22.735737     7
4   -116.847384   32.412116  -100.975944    22.289290    13
..          ...         ...          ...          ...   ...
432  -88.466935   18.508613   -88.466935    18.508613     1
433  -86.940930   21.078221   -93.137285    16.739447     1
434  -86.940930   21.078221   -92.976049    16.606635     1
435  -86.940930   21.078221   -92.860211    18.009104     2
436  -86.940930   21.078221   -92.304888    14.933672     2

[437 rows x 5 columns]

In [420]:
print(datos.columns)

Index(['id_fila_og', 'year', 'oficina_regional', 'lugar_origen',
       'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres',
       'mujeres', 'niñas', 'niños', 'regla', 'id_viaje', 'origen_limpio_mun',
       'origen_limpio_ent', 'destino_limpio_mun', 'destino_limpio_ent',
       'destino_cve', 'origen_cve', 'geom_destino', 'geom_origen',
       'lon_destino', 'lat_destino', 'lon_origen', 'lat_origen'],
      dtype='object')

# Asignación de sentidos

### Veamos las combinaciones de origenes y destinos y les asignamos un sentido manualmente en el diccionario de sentidos; luego, usamos el diccionario para asignar valores a la tabla maestra

In [421]:
combinaciones = datos[['origen_cve', 'destino_cve', 'lugar_origen', 'lugar_destino']].drop_duplicates(
    subset=['origen_cve', 'destino_cve']
)

combinaciones['sentido'] = None  

combinaciones = combinaciones.reset_index(drop=True)
combinaciones.index = combinaciones.index + 1  

with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(combinaciones)

,origen_cve,destino_cve,lugar_origen,lugar_destino,sentido
1,08035,08019,"Janos, Chihuahua","Chihuahua, Chihuahua",None
2,08035,09007,"Janos, Chihuahua","Iztapalapa, Ciudad de México",None
3,13048,09007,"Pachuca de Soto, Hidalgo","Iztapalapa, Ciudad de México",None
4,14039,30003,"Guadalajara, Jalisco","Acayucan, Veracruz",None
5,15106,09007,"Toluca, México","Iztapalapa, Ciudad de México",None
6,20327,07089,"San Pedro Tapanatepec, Oaxaca","Tapachula, Chiapas",None
7,20043,NaN,"Heroica Ciudad de Juchitán de Zaragoza, Oaxaca",Guatemala,None
8,23004,23004,"Othón P. Blanco, Quintana Roo","Othón P. Blanco, Quintana Roo",None
9,24028,09007,"San Luis Potosí, San Luis Potosí","Iztapalapa, Ciudad de México",None
10,24028,07089,"San Luis Potosí, San Luis Potosí","Tapachula, Chiapas",None
11,24028,30003,"San Luis Potosí, San Luis Potosí","Acayucan, Veracruz",None
12,28027,30003,"Nuevo Laredo, Tamaulipas","Acayucan, Veracruz",None
13,28027,09015,"Nuevo Laredo, Tamaulipas","Cuauhtémoc, Ciudad de México",None
14,28038,30003,"Tampico, Tamaulipas","Acayucan, Veracruz",None
15,32056,09007,"Zacatecas, Zacatecas","Iztapalapa, Ciudad de México",None
16,01005,09007,"Jesús María, Aguascalientes","Iztapalapa, Ciudad de México",None
17,02004,09007,"Tijuana, Baja California","Iztapalapa, Ciudad de México",None
18,04009,27017,"Escárcega, Campeche","Tenosique, Tabasco",None
19,04009,30003,"Escárcega, Campeche","Acayucan, Veracruz",None
20,04009,07089,"Escárcega, Campeche","Tapachula, Chiapas",None
21,04009,23004,"Escárcega, Campeche","Othón P. Blanco, Quintana Roo",None
22,04009,23005,"Escárcega, Campeche","Benito Juárez, Quintana Roo",None
23,04002,30003,"Campeche, Campeche","Acayucan, Veracruz",None
24,07019,07089,"Comitán de Domínguez, Chiapas","Tapachula, Chiapas",None
25,07019,NaN,"Comitán de Domínguez, Chiapas",Guatemala,None
26,07101,NaN,"Tuxtla Gutiérrez, Chiapas",Guatemala,None
27,07101,07089,"Tuxtla Gutiérrez, Chiapas","Tapachula, Chiapas",None
28,09015,07089,"Cuauhtémoc, Ciudad de México","Tapachula, Chiapas",None
29,05025,28027,"Piedras Negras, Coahuila","Nuevo Laredo, Tamaulipas",None
30,05025,09007,"Piedras Negras, Coahuila","Iztapalapa, Ciudad de México",None
31,05025,32056,"Piedras Negras, Coahuila","Zacatecas, Zacatecas",None
32,14039,09007,"Guadalajara, Jalisco","Iztapalapa, Ciudad de México",None
33,20413,07089,"Santa María Huatulco, Oaxaca","Tapachula, Chiapas",None
34,20413,NaN,"Santa María Huatulco, Oaxaca",Guatemala,None
35,20067,NaN,"Oaxaca de Juárez, Oaxaca",Guatemala,None
36,20067,30003,"Oaxaca de Juárez, Oaxaca","Acayucan, Veracruz",None
37,20067,07089,"Oaxaca de Juárez, Oaxaca","Tapachula, Chiapas",None
38,20079,30003,"Salina Cruz, Oaxaca","Acayucan, Veracruz",None
39,20079,07089,"Salina Cruz, Oaxaca","Tapachula, Chiapas",None
40,20079,NaN,"Salina Cruz, Oaxaca",Guatemala,None
41,23004,07089,"Othón P. Blanco, Quintana Roo","Tapachula, Chiapas",None
42,25012,09007,"Mazatlán, Sinaloa","Iztapalapa, Ciudad de México",None
43,27017,07089,"Tenosique, Tabasco","Tapachula, Chiapas",None
44,28032,09007,"Reynosa, Tamaulipas","Iztapalapa, Ciudad de México",None
45,28032,30003,"Reynosa, Tamaulipas","Acayucan, Veracruz",None
46,28032,07089,"Reynosa, Tamaulipas","Tapachula, Chiapas",None
47,28032,28038,"Reynosa, Tamaulipas","Tampico, Tamaulipas",None
48,28041,30003,"Ciudad Victoria, Tamaulipas","Acayucan, Veracruz",None
49,28027,09007,"Nuevo Laredo, Tamaulipas","Iztapalapa, Ciudad de México",None
50,28027,07089,"Nuevo Laredo, Tamaulipas","Tapachula, Chiapas",None
51,29002,30003,"Apetatitlán de Antonio Carvajal, Tlaxcala","Acayucan, Veracruz",None
52,29002,09007,"Apetatitlán de Antonio Carvajal, Tlaxcala","Iztapalapa, Ciudad de México",None
53,29002,19026,"Apetatitlán de Antonio Carvajal, Tlaxcala","Guadalupe, Nuevo León",None
54,30193,30003,"Veracruz, Veracruz","Acayucan, Veracruz",None
55,01005,30003,"Jesús María, Aguascalientes","Acayucan, Veracruz",None
56,02004,30003,"Tijuana, Baja California","Acayucan, Veracruz",None
57,02004,24028,"Tijuana, Baja California","San Luis Potosí, San Luis Potosí",None
58,04003,NaN,"Carmen, Campeche",Guatemala,None
59,04009,NaN,"Escárcega, Campeche",Guatemala,None
60,04002,NaN,"Campeche, Campeche",Guatemala,None
61,08035,07089,"Janos, Chihuahua","Tapachula, Chiapas",None
62,08035,30003,"Janos, Chihuahua","Acayucan, Veracruz",None
63,08037,30003,"Juárez, Chihuahua","Acayucan, Veracruz",None
64,08037,07089,"Juárez, Chihuahua","Tapachula, Chiapas",None
65,09015,07069,"Cuauhtémoc, Ciudad de México","Pijijiapan, Chiapas",None
66,09015,30003,"Cuauhtémoc, Ciudad de México","Acayucan, Veracruz",None
67,05025,30003,"Piedras Negras, Coahuila","Acayucan, Veracruz",None
68,05025,07089,"Piedras Negras, Coahuila","Tapachula, Chiapas",None
69,10007,09007,"Gómez Palacio, Durango","Iztapalapa, Ciudad de México",None
70,10007,32056,"Gómez Palacio, Durango","Zacatecas, Zacatecas",None
71,10007,NaN,"Gómez Palacio, Durango",Guatemala,None
72,13048,07089,"Pachuca de Soto, Hidalgo","Tapachula, Chiapas",None
73,13048,30003,"Pachuca de Soto, Hidalgo","Acayucan, Veracruz",None
74,16053,23004,"Morelia, Michoacán","Othón P. Blanco, Quintana Roo",None
75,16053,13048,"Morelia, Michoacán","Pachuca de Soto, Hidalgo",None
76,16053,07089,"Morelia, Michoacán","Tapachula, Chiapas",None
77,16053,09007,"Morelia, Michoacán","Iztapalapa, Ciudad de México",None
78,18017,24028,"Tepic, Nayarit","San Luis Potosí, San Luis Potosí",None
79,20067,20327,"Oaxaca de Juárez, Oaxaca","San Pedro Tapanatepec, Oaxaca",None
80,20079,20413,"Salina Cruz, Oaxaca","Santa María Huatulco, Oaxaca",None
81,23004,30003,"Othón P. Blanco, Quintana Roo","Acayucan, Veracruz",None
82,23004,NaN,"Othón P. Blanco, Quintana Roo",Guatemala,None
83,25012,30003,"Mazatlán, Sinaloa","Acayucan, Veracruz",None
84,25012,NaN,"Mazatlán, Sinaloa",Guatemala,None
85,27017,30003,"Tenosique, Tabasco","Acayucan, Veracruz",None
86,28032,32056,"Reynosa, Tamaulipas","Zacatecas, Zacatecas",None
87,28038,09007,"Tampico, Tamaulipas","Iztapalapa, Ciudad de México",None
88,28038,07089,"Tampico, Tamaulipas","Tapachula, Chiapas",None
89,28027,05030,"Nuevo Laredo, Tamaulipas","Saltillo, Coahuila de Zaragoza",None
90,29002,07089,"Apetatitlán de Antonio Carvajal, Tlaxcala","Tapachula, Chiapas",None
91,32056,30003,"Zacatecas, Zacatecas","Acayucan, Veracruz",None
92,32056,07089,"Zacatecas, Zacatecas","Tapachula, Chiapas",None
93,01005,07101,"Jesús María, Aguascalientes","Tuxtla Gutiérrez, Chiapas",None
94,02004,07089,"Tijuana, Baja California","Tapachula, Chiapas",None
95,08037,08035,"Juárez, Chihuahua","Janos, Chihuahua",None
96,08037,08037,"Juárez, Chihuahua","Juárez, Chihuahua",None
97,09015,21114,"Cuauhtémoc, Ciudad de México","Puebla, Puebla",None
98,09015,15106,"Cuauhtémoc, Ciudad de México","Toluca, México",None
99,05025,05030,"Piedras Negras, Coahuila","Saltillo, Coahuila de Zaragoza",None
100,05025,27004,"Piedras Negras, Coahuila","Centro, Tabasco",None
101,05025,19039,"Piedras Negras, Coahuila","Monterrey, Nuevo León",None
102,05025,24028,"Piedras Negras, Coahuila","San Luis Potosí, San Luis Potosí",None
103,13048,07101,"Pachuca de Soto, Hidalgo","Tuxtla Gutiérrez, Chiapas",None
104,13048,27004,"Pachuca de Soto, Hidalgo","Centro, Tabasco",None
105,14039,07089,"Guadalajara, Jalisco","Tapachula, Chiapas",None
106,20067,07101,"Oaxaca de Juárez, Oaxaca","Tuxtla Gutiérrez, Chiapas",None
107,20043,30003,"Heroica Ciudad de Juchitán de Zaragoza, Oaxaca","Acayucan, Veracruz",None
108,20043,20413,"Heroica Ciudad de Juchitán de Zaragoza, Oaxaca","Santa María Huatulco, Oaxaca",None
109,20043,07089,"Heroica Ciudad de Juchitán de Zaragoza, Oaxaca","Tapachula, Chiapas",None
110,23004,27004,"Othón P. Blanco, Quintana Roo","Centro, Tabasco",None
111,24028,32056,"San Luis Potosí, San Luis Potosí","Zacatecas, Zacatecas",None
112,24028,07101,"San Luis Potosí, San Luis Potosí","Tuxtla Gutiérrez, Chiapas",None
113,25012,07089,"Mazatlán, Sinaloa","Tapachula, Chiapas",None
114,25012,07019,"Mazatlán, Sinaloa","Comitán de Domínguez, Chiapas",None
115,25012,24028,"Mazatlán, Sinaloa","San Luis Potosí, San Luis Potosí",None
116,25012,07101,"Mazatlán, Sinaloa","Tuxtla Gutiérrez, Chiapas",None
117,27017,27004,"Tenosique, Tabasco","Centro, Tabasco",None
118,28032,07065,"Reynosa, Tamaulipas","Palenque, Chiapas",None
119,28032,27004,"Reynosa, Tamaulipas","Centro, Tabasco",None
120,28032,28032,"Reynosa, Tamaulipas","Reynosa, Tamaulipas",None
121,28032,24028,"Reynosa, Tamaulipas","San Luis Potosí, San Luis Potosí",None
122,28032,07101,"Reynosa, Tamaulipas","Tuxtla Gutiérrez, Chiapas",None
123,28032,19039,"Reynosa, Tamaulipas","Monterrey, Nuevo León",None
124,28038,24028,"Tampico, Tamaulipas","San Luis Potosí, San Luis Potosí",None
125,28038,22014,"Tampico, Tamaulipas","Querétaro, Querétaro",None
126,28038,07019,"Tampico, Tamaulipas","Comitán de Domínguez, Chiapas",None
127,28038,19039,"Tampico, Tamaulipas","Monterrey, Nuevo León",None
128,28038,26030,"Tampico, Tamaulipas","Hermosillo, Sonora",None
129,28038,27004,"Tampico, Tamaulipas","Centro, Tabasco",None
130,28038,07101,"Tampico, Tamaulipas","Tuxtla Gutiérrez, Chiapas",None
131,28027,07101,"Nuevo Laredo, Tamaulipas","Tuxtla Gutiérrez, Chiapas",None
132,28027,28038,"Nuevo Laredo, Tamaulipas","Tampico, Tamaulipas",None
133,28027,27004,"Nuevo Laredo, Tamaulipas","Centro, Tabasco",None
134,28027,NaN,"Nuevo Laredo, Tamaulipas",Guatemala,None
135,28027,24028,"Nuevo Laredo, Tamaulipas","San Luis Potosí, San Luis Potosí",None
136,30003,NaN,"Acayucan, Veracruz",Honduras,None
137,30003,07089,"Acayucan, Veracruz","Tapachula, Chiapas",None
138,30003,30003,"Acayucan, Veracruz","Acayucan, Veracruz",None
139,30003,07027,"Acayucan, Veracruz","Chiapa de Corzo, Chiapas",None
140,30003,09017,"Acayucan, Veracruz","Venustiano Carranza, Ciudad de México",None
141,30003,27004,"Acayucan, Veracruz","Centro, Tabasco",None
142,30003,09007,"Acayucan, Veracruz","Iztapalapa, Ciudad de México",None
143,30003,30108,"Acayucan, Veracruz","Minatitlán, Veracruz",None
144,32056,19039,"Zacatecas, Zacatecas","Monterrey, Nuevo León",None
145,32056,27004,"Zacatecas, Zacatecas","Centro, Tabasco",None
146,01005,24028,"Jesús María, Aguascalientes","San Luis Potosí, San Luis Potosí",None
147,01005,07089,"Jesús María, Aguascalientes","Tapachula, Chiapas",None
148,01005,27004,"Jesús María, Aguascalientes","Centro, Tabasco",None
149,01005,19039,"Jesús María, Aguascalientes","Monterrey, Nuevo León",None
150,01005,05030,"Jesús María, Aguascalientes","Saltillo, Coahuila de Zaragoza",None
151,02004,26030,"Tijuana, Baja California","Hermosillo, Sonora",None
152,07078,07089,"San Cristóbal de las Casas, Chiapas","Tapachula, Chiapas",None
153,08035,07101,"Janos, Chihuahua","Tuxtla Gutiérrez, Chiapas",None
154,08035,08037,"Janos, Chihuahua","Juárez, Chihuahua",None
155,08035,24028,"Janos, Chihuahua","San Luis Potosí, San Luis Potosí",None
156,08035,05027,"Janos, Chihuahua","Ramos Arizpe, Coahuila de Zaragoza",None
157,08035,27004,"Janos, Chihuahua","Centro, Tabasco",None
158,08037,24028,"Juárez, Chihuahua","San Luis Potosí, San Luis Potosí",None
159,08037,09007,"Juárez, Chihuahua","Iztapalapa, Ciudad de México",None
160,05030,27004,"Saltillo, Coahuila de Zaragoza","Centro, Tabasco",None
161,05030,30003,"Saltillo, Coahuila de Zaragoza","Acayucan, Veracruz",None
162,05035,27004,"Torreón, Coahuila de Zaragoza","Centro, Tabasco",None
163,05030,28038,"Saltillo, Coahuila de Zaragoza","Tampico, Tamaulipas",None
164,05018,09007,"Monclova, Coahuila de Zaragoza","Iztapalapa, Ciudad de México",None
165,05018,32056,"Monclova, Coahuila de Zaragoza","Zacatecas, Zacatecas",None
166,05018,24028,"Monclova, Coahuila de Zaragoza","San Luis Potosí, San Luis Potosí",None
167,05018,27004,"Monclova, Coahuila de Zaragoza","Centro, Tabasco",None
168,05018,30003,"Monclova, Coahuila de Zaragoza","Acayucan, Veracruz",None
169,05018,07089,"Monclova, Coahuila de Zaragoza","Tapachula, Chiapas",None
170,05018,05030,"Monclova, Coahuila de Zaragoza","Saltillo, Coahuila de Zaragoza",None
171,05025,19006,"Piedras Negras, Coahuila","Apodaca, Nuevo León",None
172,05025,19026,"Piedras Negras, Coahuila","Guadalupe, Nuevo León",None
173,05025,05018,"Piedras Negras, Coahuila","Monclova, Coahuila de Zaragoza",None
174,10007,19039,"Gómez Palacio, Durango","Monterrey, Nuevo León",None
175,10007,05027,"Gómez Palacio, Durango","Ramos Arizpe, Coahuila de Zaragoza",None
176,10007,28032,"Gómez Palacio, Durango","Reynosa, Tamaulipas",None
177,11003,09007,"San Miguel de Allende, Guanajuato","Iztapalapa, Ciudad de México",None
178,11003,24028,"San Miguel de Allende, Guanajuato","San Luis Potosí, San Luis Potosí",None
179,11003,07089,"San Miguel de Allende, Guanajuato","Tapachula, Chiapas",None
180,12001,27004,"Acapulco de Juárez, Guerrero","Centro, Tabasco",None
181,13048,19039,"Pachuca de Soto, Hidalgo","Monterrey, Nuevo León",None
182,13048,24028,"Pachuca de Soto, Hidalgo","San Luis Potosí, San Luis Potosí",None
183,14039,24028,"Guadalajara, Jalisco","San Luis Potosí, San Luis Potosí",None
184,15106,07089,"Toluca, México","Tapachula, Chiapas",None
185,15095,30003,"Tepotzotlán, México","Acayucan, Veracruz",None
186,18017,30003,"Tepic, Nayarit","Acayucan, Veracruz",None
187,18017,09007,"Tepic, Nayarit","Iztapalapa, Ciudad de México",None
188,18017,07089,"Tepic, Nayarit","Tapachula, Chiapas",None
189,20014,07089,"Ciudad Ixtepec, Oaxaca","Tapachula, Chiapas",None
190,20067,27004,"Oaxaca de Juárez, Oaxaca","Centro, Tabasco",None
191,20043,07101,"Heroica Ciudad de Juchitán de Zaragoza, Oaxaca","Tuxtla Gutiérrez, Chiapas",None
192,20043,27004,"Heroica Ciudad de Juchitán de Zaragoza, Oaxaca","Centro, Tabasco",None
193,21114,27004,"Puebla, Puebla","Centro, Tabasco",None
194,21114,07089,"Puebla, Puebla","Tapachula, Chiapas",None
195,21114,30003,"Puebla, Puebla","Acayucan, Veracruz",None
196,21114,24028,"Puebla, Puebla","San Luis Potosí, San Luis Potosí",None
197,21114,NaN,"Puebla, Puebla",Guatemala,None
198,21114,07040,"Puebla, Puebla","Huixtla, Chiapas",None
199,21114,27017,"Puebla, Puebla","Tenosique, Tabasco",None
200,23004,07101,"Othón P. Blanco, Quintana Roo","Tuxtla Gutiérrez, Chiapas",None
201,23005,07101,"Benito Juárez, Quintana Roo","Tuxtla Gutiérrez, Chiapas",None
202,23005,07089,"Benito Juárez, Quintana Roo","Tapachula, Chiapas",None
203,23005,07027,"Benito Juárez, Quintana Roo","Chiapa de Corzo, Chiapas",None
204,24028,27004,"San Luis Potosí, San Luis Potosí","Centro, Tabasco",None
205,27004,07089,"Centro, Tabasco","Tapachula, Chiapas",None
206,27004,NaN,"Centro, Tabasco",Guatemala,None
207,27004,28032,"Centro, Tabasco","Reynosa, Tamaulipas",None
208,28032,30039,"Reynosa, Tamaulipas","Coatzacoalcos, Veracruz",None
209,28032,27017,"Reynosa, Tamaulipas","Tenosique, Tabasco",None
210,28032,28027,"Reynosa, Tamaulipas","Nuevo Laredo, Tamaulipas",None
211,28032,19026,"Reynosa, Tamaulipas","Guadalupe, Nuevo León",None
212,28038,28032,"Tampico, Tamaulipas","Reynosa, Tamaulipas",None
213,28022,NaN,"Matamoros, Tamaulipas",Honduras,None
214,28022,30003,"Matamoros, Tamaulipas","Acayucan, Veracruz",None
215,28027,19026,"Nuevo Laredo, Tamaulipas","Guadalupe, Nuevo León",None
216,28027,28027,"Nuevo Laredo, Tamaulipas","Nuevo Laredo, Tamaulipas",None
217,28027,28032,"Nuevo Laredo, Tamaulipas","Reynosa, Tamaulipas",None
218,29002,27004,"Apetatitlán de Antonio Carvajal, Tlaxcala","Centro, Tabasco",None
219,29002,11007,"Apetatitlán de Antonio Carvajal, Tlaxcala","Celaya, Guanajuato",None
220,29002,20014,"Apetatitlán de Antonio Carvajal, Tlaxcala","Ciudad Ixtepec, Oaxaca",None
221,29002,30039,"Apetatitlán de Antonio Carvajal, Tlaxcala","Coatzacoalcos, Veracruz",None
222,29002,27017,"Apetatitlán de Antonio Carvajal, Tlaxcala","Tenosique, Tabasco",None
223,29002,24028,"Apetatitlán de Antonio Carvajal, Tlaxcala","San Luis Potosí, San Luis Potosí",None
224,30003,20014,"Acayucan, Veracruz","Ciudad Ixtepec, Oaxaca",None
225,31050,NaN,"Mérida, Yucatán",Guatemala,None
226,31050,07089,"Mérida, Yucatán","Tapachula, Chiapas",None
227,31050,23004,"Mérida, Yucatán","Othón P. Blanco, Quintana Roo",None
228,31050,27004,"Mérida, Yucatán","Centro, Tabasco",None
229,32056,24028,"Zacatecas, Zacatecas","San Luis Potosí, San Luis Potosí",None
230,32056,05030,"Zacatecas, Zacatecas","Saltillo, Coahuila de Zaragoza",None
231,32056,NaN,"Zacatecas, Zacatecas",Guatemala,None
232,01005,19026,"Jesús María, Aguascalientes","Guadalupe, Nuevo León",None
233,01005,11020,"Jesús María, Aguascalientes","León, Guanajuato",None
234,04009,27004,"Escárcega, Campeche","Centro, Tabasco",None
235,04002,23004,"Campeche, Campeche","Othón P. Blanco, Quintana Roo",None
236,07089,NaN,"Tapachula, Chiapas",Guatemala,None
237,07089,27004,"Tapachula, Chiapas","Centro, Tabasco",None
238,07089,30003,"Tapachula, Chiapas","Acayucan, Veracruz",None
239,07089,07101,"Tapachula, Chiapas","Tuxtla Gutiérrez, Chiapas",None
240,07089,07019,"Tapachula, Chiapas","Comitán de Domínguez, Chiapas",None
241,07087,27004,"Suchiate, Chiapas","Centro, Tabasco",None
242,07087,07101,"Suchiate, Chiapas","Tuxtla Gutiérrez, Chiapas",None
243,07009,07101,"Arriaga, Chiapas","Tuxtla Gutiérrez, Chiapas",None
244,07009,07089,"Arriaga, Chiapas","Tapachula, Chiapas",None
245,07034,07089,"Frontera Comalapa, Chiapas","Tapachula, Chiapas",None
246,07034,09015,"Frontera Comalapa, Chiapas","Cuauhtémoc, Ciudad de México",None
247,07034,NaN,"Frontera Comalapa, Chiapas",Guatemala,None
248,07078,NaN,"San Cristóbal de las Casas, Chiapas",Guatemala,None
249,07078,07040,"San Cristóbal de las Casas, Chiapas","Huixtla, Chiapas",None
250,07078,09007,"San Cristóbal de las Casas, Chiapas","Iztapalapa, Ciudad de México",None
251,08035,19006,"Janos, Chihuahua","Apodaca, Nuevo León",None
252,08035,26030,"Janos, Chihuahua","Hermosillo, Sonora",None
253,08035,32056,"Janos, Chihuahua","Zacatecas, Zacatecas",None
254,08037,26030,"Juárez, Chihuahua","Hermosillo, Sonora",None
255,09015,20327,"Cuauhtémoc, Ciudad de México","San Pedro Tapanatepec, Oaxaca",None
256,05030,32056,"Saltillo, Coahuila de Zaragoza","Zacatecas, Zacatecas",None
257,05030,09007,"Saltillo, Coahuila de Zaragoza","Iztapalapa, Ciudad de México",None
258,05018,19039,"Monclova, Coahuila de Zaragoza","Monterrey, Nuevo León",None
259,05035,19006,"Torreón, Coahuila de Zaragoza","Apodaca, Nuevo León",None
260,05035,05030,"Torreón, Coahuila de Zaragoza","Saltillo, Coahuila de Zaragoza",None
261,05035,09017,"Torreón, Coahuila de Zaragoza","Venustiano Carranza, Ciudad de México",None
262,05035,05027,"Torreón, Coahuila de Zaragoza","Ramos Arizpe, Coahuila de Zaragoza",None
263,05035,09007,"Torreón, Coahuila de Zaragoza","Iztapalapa, Ciudad de México",None
264,05035,32056,"Torreón, Coahuila de Zaragoza","Zacatecas, Zacatecas",None
265,05018,05027,"Monclova, Coahuila de Zaragoza","Ramos Arizpe, Coahuila de Zaragoza",None
266,05018,12001,"Monclova, Coahuila de Zaragoza","Acapulco de Juárez, Guerrero",None
267,05018,05035,"Monclova, Coahuila de Zaragoza","Torreón, Coahuila de Zaragoza",None
268,05018,28038,"Monclova, Coahuila de Zaragoza","Tampico, Tamaulipas",None
269,05025,05035,"Piedras Negras, Coahuila","Torreón, Coahuila de Zaragoza",None
270,05025,28032,"Piedras Negras, Coahuila","Reynosa, Tamaulipas",None
271,05025,05027,"Piedras Negras, Coahuila","Ramos Arizpe, Coahuila de Zaragoza",None
272,05025,15106,"Piedras Negras, Coahuila","Toluca, Estado de México",None
273,05025,16053,"Piedras Negras, Coahuila","Morelia, Michoacán",None
274,05025,10007,"Piedras Negras, Coahuila","Gómez Palacio, Durango",None
275,05025,22014,"Piedras Negras, Coahuila","Querétaro, Querétaro",None
276,05025,05013,"Piedras Negras, Coahuila","Hidalgo, Coahuila de Zaragoza",None
277,05025,13048,"Piedras Negras, Coahuila","Pachuca de Soto, Hidalgo",None
278,05025,25012,"Piedras Negras, Coahuila","Mazatlán, Sinaloa",None
279,05025,12001,"Piedras Negras, Coahuila","Acapulco de Juárez, Guerrero",None
280,05025,14039,"Piedras Negras, Coahuila","Guadalajara, Jalisco",None
281,05025,21114,"Piedras Negras, Coahuila","Puebla, Puebla",None

In [422]:
# Asegurar que CVEGEO sea un string con 5 caracteres
combinaciones['origen_cve'] = combinaciones['origen_cve'].astype(str).str.split('.').str[0].str.zfill(5)
combinaciones['destino_cve'] = combinaciones['destino_cve'].astype(str).str.split('.').str[0].str.zfill(5)

In [423]:
# Aplicamos el diccionario previamente asignado de manera manual con referencia al mapa de rutas generado en QGIS
dic = pd.read_parquet(REFERENCIAS / "diccionario_sentidos.parquet")

dict_sentido = (
    dic
    .drop_duplicates(subset=['origen_cve', 'destino_cve'])
    .set_index(['origen_cve', 'destino_cve'])['sentido']
    .to_dict()
)

combinaciones['sentido'] = combinaciones.apply(
    lambda x: "dep" if pd.isna(x['destino_cve']) or x['destino_cve'] == "00nan" else dict_sentido.get((x['origen_cve'], x['destino_cve'])),
    axis=1
)

In [424]:
# Verificar
combinaciones[combinaciones['sentido'].isna()]

Empty DataFrame
Columns: [origen_cve, destino_cve, lugar_origen, lugar_destino, sentido]
Index: []

In [425]:
# Aplicar a datos 
datos['origen_cve'] = datos['origen_cve'].astype('string').str.split('.').str[0].str.zfill(5)
datos['destino_cve'] = datos['destino_cve'].astype('string').str.split('.').str[0].str.zfill(5)

datos['sentido'] = datos.apply(
    lambda x: "dep" if pd.isna(x['destino_cve']) else dict_sentido.get((x['origen_cve'], x['destino_cve'])),
    axis=1
)

In [426]:
# Verificar
datos[datos['sentido'].isna()]

Empty DataFrame
Columns: [id_fila_og, year, oficina_regional, lugar_origen, lugar_destino, total_migrantes_traslado, nacionalidad, hombres, mujeres, niñas, niños, regla, id_viaje, origen_limpio_mun, origen_limpio_ent, destino_limpio_mun, destino_limpio_ent, destino_cve, origen_cve, geom_destino, geom_origen, lon_destino, lat_destino, lon_origen, lat_origen, sentido]
Index: []

[0 rows x 26 columns]

In [427]:
# Chequeo manual
datos[['sentido', 'lugar_origen', 'lugar_destino']].sample(30)

      sentido                   lugar_origen                     lugar_destino
3647      dep             Acayucan, Veracruz                          Honduras
10127     dep                Centro, Tabasco                          Honduras
9320      ret       Tijuana, Baja California      Iztapalapa, Ciudad de México
288       ret       Tijuana, Baja California      Iztapalapa, Ciudad de México
4249      ret               Janos, Chihuahua                Acayucan, Veracruz
1215      lat             Tenosique, Tabasco                Tapachula, Chiapas
440       ret       Piedras Negras, Coahuila      Iztapalapa, Ciudad de México
6064      dep             Acayucan, Veracruz                          Honduras
1908      ret            Reynosa, Tamaulipas               Tampico, Tamaulipas
10855     ret             Hermosillo, Sonora                   Centro, Tabasco
2487      ret       Tijuana, Baja California                Hermosillo, Sonora
10042     ret             Hermosillo, Sonora                 Mazatlán, Sinaloa
8154      dep                Centro, Tabasco                          Honduras
10289     ret             Acayucan, Veracruz              Minatitlán, Veracruz
7653      ret       Piedras Negras, Coahuila             Guadalupe, Nuevo León
7504      ret       Piedras Negras, Coahuila             Guadalupe, Nuevo León
667       lat             Tenosique, Tabasco                Tapachula, Chiapas
9028      dep             Acayucan, Veracruz                         Guatemala
10434     lat  Comitán de Domínguez, Chiapas                   Centro, Tabasco
10748     ret             Hermosillo, Sonora                   Centro, Tabasco
9817      ret                 Puebla, Puebla                   Centro, Tabasco
407       lat       Piedras Negras, Coahuila          Nuevo Laredo, Tamaulipas
10555     ret          Guadalupe, Nuevo León                   Centro, Tabasco
4734      ret       Piedras Negras, Coahuila               Apodaca, Nuevo León
1702      ret       Piedras Negras, Coahuila  San Luis Potosí, San Luis Potosí
9287      ret       Tijuana, Baja California              Zacatecas, Zacatecas
10753     ret             Hermosillo, Sonora                   Centro, Tabasco
9460      lat  Torreón, Coahuila de Zaragoza             Monterrey, Nuevo León
1889      ret            Reynosa, Tamaulipas               Tampico, Tamaulipas
6663      ava               Huixtla, Chiapas         Tuxtla Gutiérrez, Chiapas

# Creación de demás columnas analíticas

### Menores

In [428]:
# Creamos las columnas menores_num y menores_bin 
datos['menores_num'] = datos['niñas'] + datos['niños']

# Checar trabajo, menores_num debería = niñas + niños 
print(datos[['niñas', 'niños', 'menores_num']].head(15))

    niñas  niños  menores_num
0       0      0            0
1       0      0            0
2       9      3           12
3       6      4           10
4       2      4            6
5       0      0            0
6       7     25           32
7       4      0            4
8       5      1            6
9       3      0            3
10      1      2            3
11      3     16           19
12      1     15           16
13      4      7           11
14     17     34           51

In [429]:
# Crear menores_bin
datos['menores_bin'] = np.where(datos['menores_num'] > 0, 1, 0)

# Checar trabajo, menores_bin debería = 1 cuando hubieron menores en un dado traslado, y 0 cuando no
print(datos[['menores_num', 'menores_bin']].head(10))

   menores_num  menores_bin
0            0            0
1            0            0
2           12            1
3           10            1
4            6            1
5            0            0
6           32            1
7            4            1
8            6            1
9            3            1

### Regiones

In [430]:
# Creamos columnas binarias para mostrar la presencia / ausencia de migrantes de diferentes regiones en cada traslado
!pip install rapidfuzz
from rapidfuzz import process

Requirement already satisfied: rapidfuzz in /opt/anaconda3/lib/python3.13/site-packages (3.14.1)

In [431]:
# Creamos un diccionario para asignar los países a las regiones
nationality_to_region = {
    # Norteamérica
    'mexicana': 'norteamerica',
    'mexico': 'norteamerica',
    'estadounidense': 'norteamerica',
    'estados unidos': 'norteamerica',
    'canadiense': 'norteamerica',
    'canada': 'norteamerica',

    # Centroamérica
    'guatemalteca': 'centroamerica',
    'guatemala': 'centroamerica',
    'hondurena': 'centroamerica',
    'hondureña': 'centroamerica',
    'honduras': 'centroamerica',
    'salvadorena': 'centroamerica',
    'salvadoreña': 'centroamerica',
    'el salvador': 'centroamerica',
    'salvador': 'centroamerica',
    'nicaraguense': 'centroamerica',
    'nicaragua': 'centroamerica',
    'costarricense': 'centroamerica',
    'costa rica': 'centroamerica',
    'panamena': 'centroamerica',
    'panameña': 'centroamerica',
    'panama': 'centroamerica',
    'belice': 'centroamerica',
    'beliceña': 'centroamerica',

    # Sudamérica 
    'venezolana': 'sudamerica',
    'venezuela': 'sudamerica',
    'colombiana': 'sudamerica',
    'colombia': 'sudamerica',
    'ecuatoriana': 'sudamerica',
    'ecuador': 'sudamerica',
    'peruana': 'sudamerica',
    'peru': 'sudamerica',
    'boliviana': 'sudamerica',
    'bolivia': 'sudamerica',
    'chilena': 'sudamerica',
    'chile': 'sudamerica',
    'argentina': 'sudamerica',
    'uruguaya': 'sudamerica',
    'uruguay': 'sudamerica',
    'paraguaya': 'sudamerica',
    'paraguay': 'sudamerica',
    'brasilena': 'sudamerica',
    'brasil': 'sudamerica',
    'guyana': 'sudamerica',
    'guyanesa': 'sudamerica',
    'suriname': 'sudamerica',

    # Caribe
    'cubana': 'caribe',
    'cuba': 'caribe',
    'dominicana': 'caribe',
    'republica dominicana': 'caribe',
    'rep dominicana': 'caribe',
    'haitiana': 'caribe',
    'haiti': 'caribe',
    'puertorriquena': 'caribe',
    'puerto rico': 'caribe',
    'trinidad y tobago': 'caribe',
    'trinidad': 'caribe',
    'antillano': 'caribe',
    'antillas': 'caribe',
    'curucao': 'caribe',
    'islas virgenes': 'caribe',
    'jamaica': 'caribe',
    'jamaiquino': 'caribe',
    'bahamas': 'caribe',
    'bahameña': 'caribe',

    # Extracontinentales
    'francesa': 'extracontinentales',
    'francia': 'extracontinentales',
    'alemana': 'extracontinentales',
    'alemania': 'extracontinentales',
    'italiana': 'extracontinentales',
    'italia': 'extracontinentales',
    'japonesa': 'extracontinentales',
    'japon': 'extracontinentales',
    'china': 'extracontinentales',
    'coreana': 'extracontinentales',
    'corea': 'extracontinentales',
    'nigeriana': 'extracontinentales',
    'nigeria': 'extracontinentales',
    'india': 'extracontinentales',
    'hindu': 'extracontinentales',
    'angola': 'extracontinentales',
    'angoleña': 'extracontinentales',
    'camerun': 'extracontinentales',
    'rusia': 'extracontinentales', 
    'rusa': 'extracontinentales',
    'ucraniana': 'extracontinentales',
    'ucrania': 'extracontinentales',
    'polaca': 'extracontinentales',
    'polonia': 'extracontinentales',
    'bielorrusia': 'extracontinentales',
    'bielorusa': 'extracontinentales',
    'libanesa': 'extracontinentales',
    'libano': 'extracontinentales',
    'siria': 'extracontinentales',
    'palestina': 'extracontinentales',
    'libia': 'extracontinentales',
    'mauritania': 'extracontinentales',
    'congoleña': 'extracontinentales',
    'congo': 'extracontinentales',
    'somalia': 'extracontinentales',
    'somali': 'extracontinentales',
    'malaysia': 'extracontinentales',
    'malay': 'extracontinentales',
    'bengali': 'extracontinentales',
    'bengal': 'extracontinentales', 
    'armenia': 'extracontinentales',
    'mongol': 'extracontinentales',
    'mongolia': 'extracontinentales',
    'turca': 'extracontinentales',
    'turquia': 'extracontinentales',
    'yemeni': 'extracontinentales',
    'yemen': 'extracontinentales',
    'uzbekistan': 'extracontinentales',
    'nepali': 'extracontinentales',
    'senegal': 'extracontinentales'
}

known_nationalities = list(nationality_to_region.keys())

In [432]:
import re
from rapidfuzz import process

stopwords = {'y', 'e', 'o', 'u'}  # ignorar conectores

def fuzzy_flag_regions(nationality_str, threshold=80):
    # empezar desde 0
    region_flags = {
        'norteamerica': 0,
        'centroamerica': 0,
        'sudamerica': 0,
        'caribe': 0,
        'extracontinentales': 0,
        'nan_region': 0
    }

    # sobre NaN
    if pd.isna(nationality_str):
        return pd.Series(region_flags)
    
    nationality_str = nationality_str.strip().lower()

    # asigna filas con "varios" a NaN
    if nationality_str == 'varios':
        region_flags['nan_region'] = 1
        return pd.Series(region_flags)

    # proceso
    tokens = re.findall(r'\b[a-zA-Záéíóúñ]+\b', nationality_str)

    for token in tokens:
        if len(token) < 3 or token in stopwords:
            continue
        
        match, score, _ = process.extractOne(token, known_nationalities)
        if score >= threshold:
            region = nationality_to_region[match]
            region_flags[region] = 1
        else:
            region_flags['extracontinentales'] = 1

    return pd.Series(region_flags)

In [433]:
# Agregar regiones
region_flags_datos = datos['nacionalidad'].apply(fuzzy_flag_regions)

datos_menores_regiones = pd.concat([datos, region_flags_datos], axis=1)

In [434]:
# Limpiar ortografía
datos_menores_regiones.columns = datos_menores_regiones.columns.str.strip()

# Verificar que aparezcan las columnas que son
print(datos_menores_regiones.columns.tolist())

['id_fila_og', 'year', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'regla', 'id_viaje', 'origen_limpio_mun', 'origen_limpio_ent', 'destino_limpio_mun', 'destino_limpio_ent', 'destino_cve', 'origen_cve', 'geom_destino', 'geom_origen', 'lon_destino', 'lat_destino', 'lon_origen', 'lat_origen', 'sentido', 'menores_num', 'menores_bin', 'norteamerica', 'centroamerica', 'sudamerica', 'caribe', 'extracontinentales', 'nan_region']

In [435]:
# ¿Cuántas respuestas NaN hay?
datos_menores_regiones['nan_region'].sum()

np.int64(0)

In [436]:
# Chequeo manual de 20 filas random
pd.set_option('display.max_colwidth', None)

columns_to_show = ['nacionalidad', 'norteamerica', 'centroamerica', 'sudamerica', 'caribe', 'extracontinentales', 'nan_region']
display(datos_menores_regiones[columns_to_show].sample(20))

,nacionalidad,norteamerica,centroamerica,sudamerica,caribe,extracontinentales,nan_region
997,26 hondureños 4 guatemaltecos 02 salvadoreños,0,1,0,0,0,0
7065,"03 colombia, 14 guatemala, 01 ecuador, 02 salvadoreña",0,1,1,0,0,0
4473,40 honduras 01 guatemala,0,1,0,0,0,0
374,hondureña y dos de españa,1,1,0,0,1,0
6840,"10 haiti, 31 venezuela",0,0,1,1,0,0
2332,nicaraguense,0,1,0,0,0,0
1430,"62 honduras, 08 guatemala, 03 salvador, 02 nicaragua",0,1,0,0,0,0
5284,guatemalteca,0,1,0,0,0,0
4050,hondureña,0,1,0,0,0,0
4019,guatemalteca,0,1,0,0,0,0
4722,27 honduras,0,1,0,0,0,0
1212,"40 guatemala, 2 honduras, 1 el salvador",0,1,0,0,0,0
572,"33 honduras, 08 guatemala",0,1,0,0,0,0
9262,39 honduras,0,1,0,0,0,0
677,51 guatemala,0,1,0,0,0,0
1798,"34 honduras, 29 guatemala, 02 salvador",0,1,0,0,0,0
8099,"4 colombiana, 3 ecuatoriana, 1 guatemalteca, 8 haitiana, 1 nicaragüense, , 21 venezolana",0,1,1,1,0,0
10580,"colombiana, ecuatoriana, nicaraguense , venezolana",0,1,1,0,0,0
10145,39 guatemala,0,1,0,0,0,0
7348,"01 colombia, 02nicaragüenses, 25 hondureños, 03 salvadoreños, 09 guatemaltecos",0,1,1,0,0,0

### Diversidad regional

In [437]:
# Crear columna de diversidad - la suma de las columnas binarias de regiones - muestra de cuántas regiones venían en cada traslado

cols = ['norteamerica', 'centroamerica', 'sudamerica', 'caribe', 'nan_region', 'extracontinentales']
datos_menores_regiones['diversity'] = datos_menores_regiones[cols].sum(axis=1)

In [438]:
# Agregar columna de categorias de diversidad - sólo una región o múltiples 
datos_menores_regiones['diversity_cat'] = datos_menores_regiones['diversity'].apply(
    lambda x: 'Una región' if x == 1 else 'Dos o más regiones'
)

In [439]:
# Muestra random para chequeo manual
datos_menores_regiones[['norteamerica', 'centroamerica', 'sudamerica', 'caribe', 'nan_region', 'extracontinentales', 'diversity', 'diversity_cat']].sample(20)

,norteamerica,centroamerica,sudamerica,caribe,nan_region,extracontinentales,diversity,diversity_cat
5807,0,1,0,0,0,0,1,Una región
3308,0,1,0,0,0,0,1,Una región
2131,0,1,0,0,0,0,1,Una región
5388,0,1,0,0,0,0,1,Una región
5611,0,1,1,0,0,0,2,Dos o más regiones
8947,0,1,1,1,0,0,3,Dos o más regiones
1991,0,1,0,0,0,0,1,Una región
3204,0,1,0,0,0,0,1,Una región
492,0,1,0,0,0,0,1,Una región
4512,0,1,0,0,0,0,1,Una región
9937,0,1,1,0,0,0,2,Dos o más regiones
10384,0,1,1,1,0,1,4,Dos o más regiones
1866,0,1,0,0,0,0,1,Una región
10066,0,1,1,0,0,0,2,Dos o más regiones
9820,0,1,1,1,0,0,3,Dos o más regiones
449,0,1,0,0,0,0,1,Una región
1219,0,1,0,0,0,0,1,Una región
3266,0,1,0,0,0,0,1,Una región
4391,0,1,1,1,0,1,4,Dos o más regiones
10093,0,1,1,0,0,1,3,Dos o más regiones

In [440]:
datos_menores_regiones.to_csv(DATOS / "procesados" / "datos_analizados_condep.csv", index=False)

### Correspondencia

#### Esta tabla que importamos se hizo en base del mapa de rutas en QGIS. Hay 9 rutas documentadas (4 de sur a centro, 5 de centro al norte) y la tabla les enlista con el nombre de cada ruta y la lista extraída de los municipios y entidades a que atraviesa la línea + sus buffers de 5km

#### El proceso para el análisis de rutas se describe en el diccionario de datos, vinculado en la carpeta de documentos

In [441]:
# Primero, verificamos que cualquier NaN en columna "destino" se debe a que es una deportación
es_nulo = datos_menores_regiones['destino_cve'].isna()

es_texto_nan = (
    datos_menores_regiones['destino_cve']
    .astype(str).str.lower()
    .str.contains(r'nan|none|<na>', regex=True)
)

sin_destino = es_nulo | es_texto_nan

datos_menores_regiones.loc[sin_destino, 'lugar_destino'].unique()

array(['Guatemala', 'Honduras', 'El Salvador', 'Deportación', 'Belice',
       'Estados Unidos', 'Nicaragua'], dtype=object)

In [442]:
# Recortar tabla de datos para graficar para sólo incluir los traslados domésticos y excluir las deportaciones
datos_mx = datos_menores_regiones[~sin_destino].copy()

# Asegurar que CVEGEOs son en el formato correcto para ser interpretados
datos_mx['origen_cve'] = datos_mx['origen_cve'].astype(float).astype(int).astype(str).str.zfill(5)
datos_mx['destino_cve'] = datos_mx['destino_cve'].astype(float).astype(int).astype(str).str.zfill(5)

In [443]:
rutas = pd.read_csv(REFERENCIAS / "rutas_buff/rutas_buff_mun_master.csv")

In [444]:
# Crear diccionario para poder identificar si una localidad está o no en alguna ruta y cuál 
cvegeo_to_routes = {}

for idx, row in rutas.iterrows():
    cvegeo_list = [code.strip() for code in row['CVEGEO_lista'].split(',')]
    
    for cvegeo in cvegeo_list:
        if cvegeo not in cvegeo_to_routes:
            cvegeo_to_routes[cvegeo] = []
        cvegeo_to_routes[cvegeo].append(row['ruta'])

datos_mx['rutas_posibles_o'] = datos_mx['origen_cve'].map(
    lambda x: ', '.join(cvegeo_to_routes.get(x, []))
)

datos_mx['rutas_posibles_d'] = datos_mx['destino_cve'].map(
    lambda x: ', '.join(cvegeo_to_routes.get(x, []))
)

print(datos_mx[['lugar_origen', 'lugar_destino', 'rutas_posibles_o', 'rutas_posibles_d']].sample(20))

                                    lugar_origen  \
9304                    Tijuana, Baja California
5630                         Reynosa, Tamaulipas
980                 Cuauhtémoc, Ciudad de México
179                     Nuevo Laredo, Tamaulipas
7510                    Piedras Negras, Coahuila
10773                         Hermosillo, Sonora
31                 San Pedro Tapanatepec, Oaxaca
928                     Tijuana, Baja California
10578                      Guadalupe, Nuevo León
9697               San Pedro Tapanatepec, Oaxaca
7959                              Puebla, Puebla
10381                       Zacatecas, Zacatecas
4443              Monclova, Coahuila de Zaragoza
7655                    Piedras Negras, Coahuila
8803   Apetatitlán de Antonio Carvajal, Tlaxcala
525                            Mazatlán, Sinaloa
8555                         Tampico, Tamaulipas
9669                   Álvaro Obregón, Michoacán
2756           San Miguel de Allende, Guanajuato
2221   Apetatitlán de Antonio Carvajal, Tlaxcala

                          lugar_destino  \
9304                 Hermosillo, Sonora
5630                Tampico, Tamaulipas
980                  Tapachula, Chiapas
179        Cuauhtémoc, Ciudad de México
7510                    Centro, Tabasco
10773                   Centro, Tabasco
31                   Tapachula, Chiapas
928    San Luis Potosí, San Luis Potosí
10578                   Centro, Tabasco
9697          Tuxtla Gutiérrez, Chiapas
7959                    Centro, Tabasco
10381             Monterrey, Nuevo León
4443                    Centro, Tabasco
7655         Nava, Coahuila de Zaragoza
8803                 Tapachula, Chiapas
525        Iztapalapa, Ciudad de México
8555                    Centro, Tabasco
9669                 Morelia, Michoacán
2756       Iztapalapa, Ciudad de México
2221       Iztapalapa, Ciudad de México

                                        rutas_posibles_o  \
9304                                                baja
5630                                               golfo
980                       baja, chihuahua, sonora, tejas
179                                                tejas
7510                                               tejas
10773                                       baja, sonora
31                                     chiapas, pacifico
928                                                 baja
10578                                              tejas
9697                                   chiapas, pacifico
7959   baja, chihuahua, chiapas, pacifico, sonora, tejas
10381                                          chihuahua
4443                                               tejas
7655                                               tejas
8803
525                                         baja, sonora
8555                                        golfo, tejas
9669                                        baja, sonora
2756                                               tejas
2221

                     rutas_posibles_d
9304                     baja, sonora
5630                     golfo, tejas
980                          pacifico
179    baja, chihuahua, sonora, tejas
7510                  caribe, tabasco
10773                 caribe, tabasco
31                           pacifico
928                             tejas
10578                 caribe, tabasco
9697
7959                  caribe, tabasco
10381                           tejas
4443                  caribe, tabasco
7655                            tejas
8803                         pacifico
525    baja, chihuahua, sonora, tejas
8555                  caribe, tabasco
9669                     baja, sonora
2756   baja, chihuahua, sonora, tejas
2221   baja, chihuahua, sonora, tejas

In [445]:
# Si no hubo rutas posibles, poner "ninguna"
datos_mx['rutas_posibles_o'] = datos_mx['rutas_posibles_o'].replace('', 'ninguna')
datos_mx['rutas_posibles_d'] = datos_mx['rutas_posibles_d'].replace('', 'ninguna')

In [446]:
# Agrupar rutas en nortes y sures
rutas_norte = {'baja', 'sonora', 'chihuahua', 'tejas', 'golfo'}
rutas_sur = {'pacifico', 'chiapas', 'tabasco', 'caribe'}

def get_route_set(route_string):
    """Convert 'ruta1, ruta2' to {'ruta1', 'ruta2'}"""
    if route_string == 'ninguna' or route_string == '' or pd.isna(route_string):
        return set()
    return {r.strip().lower() for r in route_string.split(',') if r.strip()}

# Definir correspondencia entre rutas de origen y rutas de destino
def clasificar_correspondencia(row):
    rutas_o = get_route_set(row['rutas_posibles_o'])
    rutas_d = get_route_set(row['rutas_posibles_d'])
    
   # Casos con un valor "ninguna"
    if not rutas_o and not rutas_d:
        return 'ambos_fuera'
    if not rutas_o:
        return 'o_fuera'
    if not rutas_d:
        return 'd_fuera'

    # Casos de coincidencia
    if rutas_o & rutas_d: 
        return 'ruta_cont_1'
    
    # Checar norte y sur
    o_is_norte = rutas_o.issubset(rutas_norte)
    o_is_sur = rutas_o.issubset(rutas_sur)
    d_is_norte = rutas_d.issubset(rutas_norte)
    d_is_sur = rutas_d.issubset(rutas_sur)
    
    # Uno y uno; casos particulares de rutas definidas como principales
    if (o_is_norte and d_is_sur) or (o_is_sur and d_is_norte):
        # Checar si está pacifico O (tabasco y golfo)
        todas_rutas = rutas_o | rutas_d
        if 'pacifico' in todas_rutas or ('tabasco' in todas_rutas and 'golfo' in todas_rutas):
            return 'ruta_cont_1'
        else:
            return 'ruta_cont_2'
    
    # Dos nortes o dos sures
    if (o_is_norte and d_is_norte) or (o_is_sur and d_is_sur):
        return 'rutas_diferentes'
    
    # Fallas
    return 'ERROR'

# Crear columna
datos_mx['correspondencia'] = datos_mx.apply(clasificar_correspondencia, axis=1)

# Checar resultados
print(datos_mx[['rutas_posibles_o', 'rutas_posibles_d', 'correspondencia']].head(20))

# Checar errores
print("\nCorrespondencia:")
print(datos_mx['correspondencia'].value_counts())

           rutas_posibles_o                rutas_posibles_d correspondencia
0                   ninguna                       chihuahua         o_fuera
1                   ninguna                       chihuahua         o_fuera
2                   ninguna  baja, chihuahua, sonora, tejas         o_fuera
3                   ninguna  baja, chihuahua, sonora, tejas         o_fuera
4                   ninguna                       chihuahua         o_fuera
5                   ninguna                       chihuahua         o_fuera
6                   ninguna  baja, chihuahua, sonora, tejas         o_fuera
7              baja, sonora                 caribe, tabasco     ruta_cont_2
8              baja, sonora                 caribe, tabasco     ruta_cont_2
9              baja, sonora                 caribe, tabasco     ruta_cont_2
10  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
11  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
12  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
13  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
14  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
15  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
16  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
17  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
18  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1
19  baja, chihuahua, sonora  baja, chihuahua, sonora, tejas     ruta_cont_1

Correspondencia:
correspondencia
ruta_cont_1         3917
ruta_cont_2         1887
rutas_diferentes    1129
o_fuera             1093
d_fuera              526
ERROR                262
ambos_fuera           15
Name: count, dtype: int64

In [447]:
# Revisar nombres de municipio cuando hubo errores
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

errores = datos_mx[datos_mx['correspondencia'] == 'ERROR'][['lugar_origen', 'lugar_destino']]
print(errores)

print(f"\nErrores: {len(errores)}")

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

            lugar_origen       lugar_destino
2825      Puebla, Puebla     Centro, Tabasco
2830      Puebla, Puebla     Centro, Tabasco
2831      Puebla, Puebla     Centro, Tabasco
2832      Puebla, Puebla     Centro, Tabasco
2833      Puebla, Puebla     Centro, Tabasco
2836      Puebla, Puebla     Centro, Tabasco
2838      Puebla, Puebla     Centro, Tabasco
2840      Puebla, Puebla     Centro, Tabasco
2845      Puebla, Puebla     Centro, Tabasco
2848      Puebla, Puebla     Centro, Tabasco
2849      Puebla, Puebla     Centro, Tabasco
2850      Puebla, Puebla  Acayucan, Veracruz
2852      Puebla, Puebla     Centro, Tabasco
2853      Puebla, Puebla  Acayucan, Veracruz
2855      Puebla, Puebla  Acayucan, Veracruz
2858      Puebla, Puebla  Acayucan, Veracruz
2860      Puebla, Puebla  Acayucan, Veracruz
2867      Puebla, Puebla     Centro, Tabasco
2868      Puebla, Puebla     Centro, Tabasco
2878      Puebla, Puebla     Centro, Tabasco
2887      Puebla, Puebla     Centro, Tabasco
2969      Puebla, Puebla     Centro, Tabasco
2973      Puebla, Puebla     Centro, Tabasco
2993      Puebla, Puebla  Tenosique, Tabasco
4874      Puebla, Puebla  Acayucan, Veracruz
4875      Puebla, Puebla  Acayucan, Veracruz
4876      Puebla, Puebla  Acayucan, Veracruz
4877      Puebla, Puebla  Acayucan, Veracruz
4879      Puebla, Puebla  Acayucan, Veracruz
4880      Puebla, Puebla  Acayucan, Veracruz
4881      Puebla, Puebla  Acayucan, Veracruz
4882      Puebla, Puebla  Acayucan, Veracruz
4889      Puebla, Puebla     Centro, Tabasco
4890      Puebla, Puebla     Centro, Tabasco
4891      Puebla, Puebla     Centro, Tabasco
4892      Puebla, Puebla     Centro, Tabasco
4893      Puebla, Puebla     Centro, Tabasco
4894      Puebla, Puebla     Centro, Tabasco
4895      Puebla, Puebla     Centro, Tabasco
4896      Puebla, Puebla  Acayucan, Veracruz
4897      Puebla, Puebla  Acayucan, Veracruz
4898      Puebla, Puebla  Acayucan, Veracruz
4899      Puebla, Puebla  Acayucan, Veracruz
4900      Puebla, Puebla  Acayucan, Veracruz
4901      Puebla, Puebla  Acayucan, Veracruz
4902      Puebla, Puebla  Acayucan, Veracruz
4903      Puebla, Puebla  Acayucan, Veracruz
4904      Puebla, Puebla  Acayucan, Veracruz
4907      Puebla, Puebla     Centro, Tabasco
4908      Puebla, Puebla     Centro, Tabasco
4909      Puebla, Puebla     Centro, Tabasco
6133  Acayucan, Veracruz      Puebla, Puebla
7921      Puebla, Puebla     Centro, Tabasco
7925      Puebla, Puebla     Centro, Tabasco
7946      Puebla, Puebla  Tenosique, Tabasco
7958      Puebla, Puebla     Centro, Tabasco
7959      Puebla, Puebla     Centro, Tabasco
7960      Puebla, Puebla     Centro, Tabasco
7961      Puebla, Puebla     Centro, Tabasco
7962      Puebla, Puebla     Centro, Tabasco
7963      Puebla, Puebla     Centro, Tabasco
7967      Puebla, Puebla     Centro, Tabasco
7970      Puebla, Puebla     Centro, Tabasco
7971      Puebla, Puebla     Centro, Tabasco
7973      Puebla, Puebla     Centro, Tabasco
7974      Puebla, Puebla     Centro, Tabasco
7975      Puebla, Puebla     Centro, Tabasco
7977      Puebla, Puebla     Centro, Tabasco
7981      Puebla, Puebla     Centro, Tabasco
7982      Puebla, Puebla     Centro, Tabasco
7983      Puebla, Puebla     Centro, Tabasco
7985      Puebla, Puebla     Centro, Tabasco
7987      Puebla, Puebla     Centro, Tabasco
7990      Puebla, Puebla     Centro, Tabasco
8003      Puebla, Puebla     Centro, Tabasco
8004      Puebla, Puebla     Centro, Tabasco
8005      Puebla, Puebla     Centro, Tabasco
8006      Puebla, Puebla     Centro, Tabasco
8007      Puebla, Puebla     Centro, Tabasco
8008      Puebla, Puebla     Centro, Tabasco
8009      Puebla, Puebla     Centro, Tabasco
8010      Puebla, Puebla     Centro, Tabasco
8011      Puebla, Puebla     Centro, Tabasco
8012      Puebla, Puebla     Centro, Tabasco
8024      Puebla, Puebla     Centro, Tabasco
8025      Puebla, Puebla     Centro, Tabasco
8026      Puebla, Puebla     Centro, Tabasco
8027      Puebla, Puebla     Centro, Tabasco
8028      Puebla, Puebla     Centro, Tabasco
8029      Puebla, Puebla     Centro, Tabasco
8030      Puebla, Puebla  Acayucan, Veracruz
8032      Puebla, Puebla  Acayucan, Veracruz
8033      Puebla, Puebla  Acayucan, Veracruz
8035      Puebla, Puebla     Centro, Tabasco
8036      Puebla, Puebla     Centro, Tabasco
8037      Puebla, Puebla     Centro, Tabasco
8038      Puebla, Puebla     Centro, Tabasco
8039      Puebla, Puebla     Centro, Tabasco
8040      Puebla, Puebla  Acayucan, Veracruz
8041      Puebla, Puebla  Acayucan, Veracruz
8042      Puebla, Puebla     Centro, Tabasco
8043      Puebla, Puebla     Centro, Tabasco
8045      Puebla, Puebla     Centro, Tabasco
8046      Puebla, Puebla     Centro, Tabasco
8047      Puebla, Puebla     Centro, Tabasco
8049      Puebla, Puebla     Centro, Tabasco
8050      Puebla, Puebla     Centro, Tabasco
8051      Puebla, Puebla     Centro, Tabasco
8052      Puebla, Puebla     Centro, Tabasco
8053      Puebla, Puebla  Acayucan, Veracruz
8054      Puebla, Puebla     Centro, Tabasco
8055      Puebla, Puebla     Centro, Tabasco
8056      Puebla, Puebla     Centro, Tabasco
8057      Puebla, Puebla  Acayucan, Veracruz
8058      Puebla, Puebla  Acayucan, Veracruz
8059      Puebla, Puebla  Acayucan, Veracruz
8060      Puebla, Puebla     Centro, Tabasco
8061      Puebla, Puebla  Acayucan, Veracruz
8062      Puebla, Puebla  Acayucan, Veracruz
9795      Puebla, Puebla     Centro, Tabasco
9796      Puebla, Puebla     Centro, Tabasco
9797      Puebla, Puebla     Centro, Tabasco
9798      Puebla, Puebla     Centro, Tabasco
9799      Puebla, Puebla     Centro, Tabasco
9800      Puebla, Puebla     Centro, Tabasco
9801      Puebla, Puebla     Centro, Tabasco
9802      Puebla, Puebla     Centro, Tabasco
9803      Puebla, Puebla     Centro, Tabasco
9804      Puebla, Puebla     Centro, Tabasco
9805      Puebla, Puebla     Centro, Tabasco
9806      Puebla, Puebla     Centro, Tabasco
9807      Puebla, Puebla     Centro, Tabasco
9808      Puebla, Puebla     Centro, Tabasco
9809      Puebla, Puebla     Centro, Tabasco
9810      Puebla, Puebla     Centro, Tabasco
9811      Puebla, Puebla     Centro, Tabasco
9812      Puebla, Puebla     Centro, Tabasco
9813      Puebla, Puebla     Centro, Tabasco
9814      Puebla, Puebla     Centro, Tabasco
9815      Puebla, Puebla     Centro, Tabasco
9816      Puebla, Puebla     Centro, Tabasco
9817      Puebla, Puebla     Centro, Tabasco
9818      Puebla, Puebla     Centro, Tabasco
9819      Puebla, Puebla     Centro, Tabasco
9820      Puebla, Puebla     Centro, Tabasco
9821      Puebla, Puebla     Centro, Tabasco
9822      Puebla, Puebla     Centro, Tabasco
9823      Puebla, Puebla     Centro, Tabasco
9824      Puebla, Puebla     Centro, Tabasco
9825      Puebla, Puebla     Centro, Tabasco
9826      Puebla, Puebla     Centro, Tabasco
9827      Puebla, Puebla     Centro, Tabasco
9828      Puebla, Puebla     Centro, Tabasco
9829      Puebla, Puebla     Centro, Tabasco
9830      Puebla, Puebla     Centro, Tabasco
9831      Puebla, Puebla     Centro, Tabasco
9832      Puebla, Puebla     Centro, Tabasco
9833      Puebla, Puebla     Centro, Tabasco
9834      Puebla, Puebla     Centro, Tabasco
9835      Puebla, Puebla     Centro, Tabasco
9836      Puebla, Puebla     Centro, Tabasco
9837      Puebla, Puebla     Centro, Tabasco
9838      Puebla, Puebla     Centro, Tabasco
9839      Puebla, Puebla     Centro, Tabasco
9840      Puebla, Puebla     Centro, Tabasco
9841      Puebla, Puebla     Centro, Tabasco
9842      Puebla, Puebla     Centro, Tabasco
9843      Puebla, Puebla     Centro, Tabasco
9844      Puebla, Puebla     Centro, Tabasco
9845      Puebla, Puebla     Centro, Tabasco
9846      Puebla, Puebla     Centro, Tabasco
9847      Puebla, Puebla     Centro, Tabasco
9848      Puebla, Puebla     Centro, Tabasco
9849      Puebla, Puebla     Centro, Tabasco
9850      Puebla, Puebla     Centro, Tabasco
9851      Puebla, Puebla     Centro, Tabasco
9852      Puebla, Puebla     Centro, Tabasco
9853      Puebla, Puebla     Centro, Tabasco
9854      Puebla, Puebla     Centro, Tabasco
9855      Puebla, Puebla     Centro, Tabasco
9856      Puebla, Puebla     Centro, Tabasco
9857      Puebla, Puebla     Centro, Tabasco
9858      Puebla, Puebla     Centro, Tabasco
9859      Puebla, Puebla     Centro, Tabasco
9860      Puebla, Puebla     Centro, Tabasco
9861      Puebla, Puebla     Centro, Tabasco
9862      Puebla, Puebla     Centro, Tabasco
9863      Puebla, Puebla     Centro, Tabasco
9864      Puebla, Puebla     Centro, Tabasco
9865      Puebla, Puebla     Centro, Tabasco
9866      Puebla, Puebla     Centro, Tabasco
9867      Puebla, Puebla     Centro, Tabasco
9868      Puebla, Puebla     Centro, Tabasco
9869      Puebla, Puebla     Centro, Tabasco
9870      Puebla, Puebla     Centro, Tabasco
9871      Puebla, Puebla     Centro, Tabasco
9872      Puebla, Puebla     Centro, Tabasco
9873      Puebla, Puebla     Centro, Tabasco
9874      Puebla, Puebla     Centro, Tabasco
9875      Puebla, Puebla     Centro, Tabasco
9876      Puebla, Puebla     Centro, Tabasco
9877      Puebla, Puebla     Centro, Tabasco
9878      Puebla, Puebla     Centro, Tabasco
9879      Puebla, Puebla     Centro, Tabasco
9880      Puebla, Puebla     Centro, Tabasco
9881      Puebla, Puebla     Centro, Tabasco
9882      Puebla, Puebla     Centro, Tabasco
9883      Puebla, Puebla     Centro, Tabasco
9884      Puebla, Puebla     Centro, Tabasco
9885      Puebla, Puebla     Centro, Tabasco
9886      Puebla, Puebla     Centro, Tabasco
9887      Puebla, Puebla     Centro, Tabasco
9888      Puebla, Puebla     Centro, Tabasco
9889      Puebla, Puebla     Centro, Tabasco
9890      Puebla, Puebla     Centro, Tabasco
9891      Puebla, Puebla     Centro, Tabasco
9892      Puebla, Puebla     Centro, Tabasco
9893      Puebla, Puebla     Centro, Tabasco
9894      Puebla, Puebla     Centro, Tabasco
9895      Puebla, Puebla     Centro, Tabasco
9896      Puebla, Puebla     Centro, Tabasco
9897      Puebla, Puebla     Centro, Tabasco
9898      Puebla, Puebla     Centro, Tabasco
9899      Puebla, Puebla     Centro, Tabasco
9900      Puebla, Puebla     Centro, Tabasco
9901      Puebla, Puebla     Centro, Tabasco
9902      Puebla, Puebla     Centro, Tabasco
9903      Puebla, Puebla     Centro, Tabasco
9904      Puebla, Puebla     Centro, Tabasco
9905      Puebla, Puebla     Centro, Tabasco
9906      Puebla, Puebla     Centro, Tabasco
9907      Puebla, Puebla     Centro, Tabasco
9908      Puebla, Puebla     Centro, Tabasco
9909      Puebla, Puebla     Centro, Tabasco
9910      Puebla, Puebla     Centro, Tabasco
9911      Puebla, Puebla     Centro, Tabasco
9912      Puebla, Puebla     Centro, Tabasco
9913      Puebla, Puebla     Centro, Tabasco
9914      Puebla, Puebla     Centro, Tabasco
9915      Puebla, Puebla     Centro, Tabasco
9916      Puebla, Puebla     Centro, Tabasco
9917      Puebla, Puebla     Centro, Tabasco
9918      Puebla, Puebla     Centro, Tabasco
9919      Puebla, Puebla     Centro, Tabasco
9920      Puebla, Puebla     Centro, Tabasco
9921      Puebla, Puebla     Centro, Tabasco
9922      Puebla, Puebla     Centro, Tabasco
9923      Puebla, Puebla     Centro, Tabasco
9924      Puebla, Puebla     Centro, Tabasco
9925      Puebla, Puebla     Centro, Tabasco
9926      Puebla, Puebla     Centro, Tabasco
9927      Puebla, Puebla     Centro, Tabasco
9928      Puebla, Puebla     Centro, Tabasco
9929      Puebla, Puebla     Centro, Tabasco
9930      Puebla, Puebla     Centro, Tabasco
9931      Puebla, Puebla     Centro, Tabasco
9932      Puebla, Puebla     Centro, Tabasco
9933      Puebla, Puebla     Centro, Tabasco
9934      Puebla, Puebla     Centro, Tabasco
9935      Puebla, Puebla     Centro, Tabasco
9936      Puebla, Puebla     Centro, Tabasco
9937      Puebla, Puebla     Centro, Tabasco

Errores: 262

#### Muchos de los errores eran porque hay un punto conector entre las redes de rutas del norte y del sur: Puebla. Hay que clasificarlo como parte de una red o la otra. La sacaremos de las rutas del sur

In [448]:
rutas_sur_names = ['pacifico', 'chiapas', 'tabasco', 'caribe']

for ruta_name in rutas_sur_names:
    # Actualiarzar CVEGEO_lista - sacar 21114
    rutas.loc[rutas['ruta'] == ruta_name, 'CVEGEO_lista'] = rutas.loc[rutas['ruta'] == ruta_name, 'CVEGEO_lista'].str.replace(r',?\s*21114\s*,?', '', regex=True).str.strip(', ')
    
    # Actualizar municipio_nombre - sacar Puebla
    rutas.loc[rutas['ruta'] == ruta_name, 'municipios_nombre'] = rutas.loc[rutas['ruta'] == ruta_name, 'municipios_nombre'].str.replace(r',?\s*Puebla\s*,?', '', regex=True).str.strip(', ')

# Verificar
print(rutas[rutas['ruta'].isin(rutas_sur_names)][['ruta', 'CVEGEO_lista', 'municipios_nombre']])

       ruta                                       CVEGEO_lista  \
1    caribe  04003, 04007, 04004, 04002, 04006, 07074, 2027...
3   chiapas  07019, 07108, 07106, 07104, 07075, 07086, 0708...
5  pacifico  07103, 07102, 07057, 07054, 07051, 07070, 0705...
7   tabasco  07074, 07050, 07065, 07077, 07016, 20278, 2018...

                                   municipios_nombre
1  Carmen, Palizada, Champotón, Campeche, Hopelch...
3  Comitán de Domínguez, Villaflores, Venustiano ...
5  Tuzantán, Tuxtla Chico, Motozintla, Mazatán, M...
7  Reforma, La Libertad, Palenque, Salto de Agua,...

In [449]:
# Rehacer diccionario de rutas
cvegeo_to_routes = {}

for idx, row in rutas.iterrows():
    cvegeo_list = [code.strip() for code in row['CVEGEO_lista'].split(',')]
    for cvegeo in cvegeo_list:
        if cvegeo not in cvegeo_to_routes:
            cvegeo_to_routes[cvegeo] = []
        cvegeo_to_routes[cvegeo].append(row['ruta'])

datos_mx['rutas_posibles_o'] = datos_mx['origen_cve'].map(
    lambda x: ', '.join(cvegeo_to_routes.get(x, [])) or 'ninguna'
)

datos_mx['rutas_posibles_d'] = datos_mx['destino_cve'].map(
    lambda x: ', '.join(cvegeo_to_routes.get(x, [])) or 'ninguna'
)

# Recalcular
datos_mx['correspondencia'] = datos_mx.apply(clasificar_correspondencia, axis=1)

# Checar errores
print(datos_mx['correspondencia'].value_counts())

correspondencia
ruta_cont_1         3917
ruta_cont_2         2149
rutas_diferentes    1129
o_fuera             1093
d_fuera              526
ambos_fuera           15
Name: count, dtype: int64

In [450]:
# Checar lugar_origen donde correspondencia es o_fuera
origenes_fuera = datos_mx[datos_mx['correspondencia'] == 'o_fuera']['lugar_origen'].unique()
print("Orígenes fuera de ruta:")
print(list(origenes_fuera))
print(f"\nTotal: {len(origenes_fuera)}")

print("\n" + "="*50 + "\n")

# Checar lugar_destino donde correspondencia es d_fuera
destinos_fuera = datos_mx[datos_mx['correspondencia'] == 'd_fuera']['lugar_destino'].unique()
print("Destinos fuera de ruta:")
print(list(destinos_fuera))
print(f"\nTotal: {len(destinos_fuera)}")

Orígenes fuera de ruta:
['Janos, Chihuahua', 'Pachuca de Soto, Hidalgo', 'Escárcega, Campeche', 'Tuxtla Gutiérrez, Chiapas', 'Santa María Huatulco, Oaxaca', 'Salina Cruz, Oaxaca', 'Othón P. Blanco, Quintana Roo', 'Apetatitlán de Antonio Carvajal, Tlaxcala', 'San Cristóbal de las Casas, Chiapas', 'Acapulco de Juárez, Guerrero', 'Mérida, Yucatán', 'Guanajuato, Guanajuato', 'Apaxco, México', 'Tlaxcala, Tlaxcala']

Total: 14

==================================================

Destinos fuera de ruta:
['Othón P. Blanco, Quintana Roo', 'Pachuca de Soto, Hidalgo', 'Tuxtla Gutiérrez, Chiapas', 'Janos, Chihuahua', 'Santa María Huatulco, Oaxaca', 'Acapulco de Juárez, Guerrero', 'Hidalgo, Coahuila de Zaragoza', 'San Cristóbal de las Casas, Chiapas', 'Durango, Durango', 'Lázaro Cárdenas, Michoacán', 'Berriozábal, Chiapas']

Total: 11

In [451]:
main_routes = ['pacifico', 'baja', 'sonora', 'chihuahua', 'tejas', 'golfo']

def map_correspondencia(row):
    val = row['correspondencia']
    if val in ['rutas_diferentes', 'ruta_cont_2']:
        return 'Entre rutas paralelas o alternativas'
    elif val == 'ruta_cont_1':
        return 'Sobre una ruta principal'
    elif val == 'o_fuera':
        rutasd = row['rutas_posibles_d']
        if rutasd == 'ninguna':
            return 'Terminar fuera de cualquier ruta'
        rutas_list = [r.strip() for r in rutasd.split(',')]
        if any(r in main_routes for r in rutas_list):
            return 'Sobre una ruta principal'
        else:
            return 'Entre rutas paralelas o alternativas'
    elif val in ['d_fuera', 'ambos_fuera']:
        return 'Terminar fuera de cualquier ruta'

datos_mx['correspondencia_bin'] = datos_mx.apply(map_correspondencia, axis=1)

print(datos_mx['correspondencia_bin'].value_counts())

correspondencia_bin
Sobre una ruta principal                4627
Entre rutas paralelas o alternativas    3661
Terminar fuera de cualquier ruta         541
Name: count, dtype: int64

### Infraestructura de detención

##### Esta tabla que importamos muestra el municipio, entidad, tipo de estancia y año de inicio de operaciones para cada estancia provisional y estación migratoria documentada por la CNDH. Las instalaciones para las cuales la fecha de inicio de operaciones es desconocida son anotadas en 0.

In [452]:
em = pd.read_csv(REFERENCIAS / 'EMs.csv')

#### Creamos columnas que describen la presencia de infraestructura de detención migratoria en origenes y destinos

In [453]:
# Corregir formatos de CVEGEO
em['CVEGEO'] = em['CVEGEO'].astype(str).str.zfill(5)

# Extraer CVEGEOS de df ems
em_cvegeos = set(em['CVEGEO'].unique())

# Crear em_o columna: 1 si origen_CVEGEO está en ems, 0 si no
datos_mx['em_o'] = datos_mx['origen_cve'].isin(em_cvegeos).astype(int)

# Crear em_d columna: 1 si destino_CVEGEO está en ems, 0 si no
datos_mx['em_d'] = datos_mx['destino_cve'].isin(em_cvegeos).astype(int)

# Checar resultado
columns_to_show = ['lugar_destino', 'lugar_origen', 'em_o', 'em_d']
print(datos_mx[columns_to_show].sample(20))

                      lugar_destino  \
3587             Tenosique, Tabasco
6616      Tuxtla Gutiérrez, Chiapas
7288       Pachuca de Soto, Hidalgo
1079   Iztapalapa, Ciudad de México
2928             Tapachula, Chiapas
4439   Iztapalapa, Ciudad de México
2562             Tapachula, Chiapas
5128                Centro, Tabasco
2770   Iztapalapa, Ciudad de México
749              Acayucan, Veracruz
8589                Centro, Tabasco
8537                Centro, Tabasco
10612               Centro, Tabasco
8775                Centro, Tabasco
2547   Iztapalapa, Ciudad de México
9957                Centro, Tabasco
704              Acayucan, Veracruz
5066                Centro, Tabasco
3443             Acayucan, Veracruz
954              Tapachula, Chiapas

                                    lugar_origen  em_o  em_d
3587   Apetatitlán de Antonio Carvajal, Tlaxcala     0     0
6616                          Huehuetán, Chiapas     1     1
7288                    Piedras Negras, Coahuila     1     1
1079                    Pachuca de Soto, Hidalgo     1     1
2928                              Puebla, Puebla     1     1
4439              Monclova, Coahuila de Zaragoza     1     1
2562                           Juárez, Chihuahua     0     1
5128                          Hermosillo, Sonora     1     1
2770                    Pachuca de Soto, Hidalgo     1     1
749                          Tampico, Tamaulipas     1     1
8589                    Nuevo Laredo, Tamaulipas     1     1
8537                         Tampico, Tamaulipas     1     1
10612                      Guadalupe, Nuevo León     1     1
8775                         Tampico, Tamaulipas     1     1
2547                            Janos, Chihuahua     1     1
9957                           Mazatlán, Sinaloa     1     1
704                          Reynosa, Tamaulipas     1     1
5066                          Hermosillo, Sonora     1     1
3443   Apetatitlán de Antonio Carvajal, Tlaxcala     0     1
954                            Juárez, Chihuahua     0     1

In [454]:
# Crear columna em_s para analizar infraestructura de detención migratoria 
def clasificar_ems(row):
    suma = row['em_o'] + row['em_d']
    
    if suma == 0:
        return 'no_em'
    elif suma == 1:
        if row['em_o'] == 1:
            return 'em_o'
        else:
            return 'em_d'
    elif suma == 2:
        return 'ambos'
    else:
        return 'ERROR'  

datos_mx['ems'] = datos_mx.apply(clasificar_ems, axis=1)

# Checar resultado 
print(datos_mx[['em_o', 'em_d', 'ems']].sample(20))

# Y distribución
print("\nDistribución ems:")
print(datos_mx['ems'].value_counts())

      em_o  em_d    ems
7549     1     1  ambos
5698     1     1  ambos
8328     1     0   em_o
6703     1     1  ambos
6888     1     1  ambos
38       0     1   em_d
4607     1     1  ambos
7804     1     1  ambos
1148     1     1  ambos
322      1     1  ambos
1475     1     1  ambos
3434     1     1  ambos
2379     1     1  ambos
9660     0     1   em_d
3074     1     1  ambos
7430     1     1  ambos
5723     1     1  ambos
1561     1     1  ambos
9472     1     1  ambos
278      1     1  ambos

Distribución ems:
ems
ambos    6621
em_d     1496
em_o      581
no_em     131
Name: count, dtype: int64

In [455]:
# Haremos que la columna ems tome en cuenta la fecha de inicio de operaciones cuando sea posible
cvegeo_to_operaciones = dict(zip(em['CVEGEO'], em['operaciones_desde']))

# Recalcular em_o
def check_em_o(row):
    cvegeo = row['origen_cve']
    if cvegeo in cvegeo_to_operaciones:
        if row['year'] >= cvegeo_to_operaciones[cvegeo]:
            return 1
    return 0

# Recalcular em_d
def check_em_d(row):
    cvegeo = row['destino_cve']
    if cvegeo in cvegeo_to_operaciones:
        if row['year'] >= cvegeo_to_operaciones[cvegeo]:
            return 1
    return 0

# Aplicar
datos_mx['em_o'] = datos_mx.apply(check_em_o, axis=1)
datos_mx['em_d'] = datos_mx.apply(check_em_d, axis=1)

# Recalcular ems
datos_mx['ems'] = datos_mx.apply(clasificar_ems, axis=1)

# Y distribución
print("\nDistribución ems:")
print(datos_mx['ems'].value_counts())

Distribución ems:
ems
ambos    5811
em_d     2117
em_o      646
no_em     255
Name: count, dtype: int64

In [456]:
# Checar resultados
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

print(datos_mx[['id_fila_og', 'year', 'origen_limpio_mun', 'destino_limpio_mun', 'em_o', 'em_d', 'ems']].sample(30))

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

       id_fila_og  year     origen_limpio_mun destino_limpio_mun  em_o  em_d  \
2304         2555  2020              Acayucan          Tapachula     1     1
149           163  2017          Nuevo Laredo         Cuauhtémoc     1     0
7015         8246  2023                 Janos         Iztapalapa     1     1
220           234  2017               Tampico           Acayucan     0     1
7402         8641  2023        Piedras Negras            Morelia     1     1
3048         3365  2021              Mazatlán          Tapachula     1     1
6860         8075  2023               Huixtla          Tapachula     1     1
7461         8700  2023        Piedras Negras          Guadalupe     1     1
9217        12355  2023              Acayucan   Tuxtla Gutiérrez     1     1
6534         7745  2023             Huehuetán   Tuxtla Gutiérrez     1     1
2936         3231  2021                Puebla          Tapachula     1     1
10290       13763  2024              Acayucan         Minatitlán     1     0
10832       11243  2023            Hermosillo             Centro     1     1
4563         5149  2022        Piedras Negras       Ramos Arizpe     1     0
1504         1632  2019          Nuevo Laredo           Saltillo     1     1
6465         7676  2023             Huehuetán          Tapachula     1     1
9845        13318  2024                Puebla             Centro     1     1
9626        12815  2024           Guadalajara             Centro     1     1
7129         8361  2023        Piedras Negras             Centro     1     1
10452        2764  2021  Comitán de Domínguez             Centro     1     1
8562        11695  2023               Tampico             Centro     1     1
4254         4814  2022                 Janos             Centro     1     1
7578         8819  2023        Piedras Negras             Centro     1     1
1182         1277  2019       San Luis Potosí           Acayucan     1     1
9618        12807  2024           Guadalajara             Centro     1     1
9492        12681  2024        Piedras Negras             Centro     1     1
529           568  2018              Mazatlán         Iztapalapa     1     1
6639         7852  2023              Suchiate   Tuxtla Gutiérrez     0     1
10167       13640  2024               Reynosa            Reynosa     1     1
8336        11469  2023              Palenque             Centro     1     1

         ems
2304   ambos
149     em_o
7015   ambos
220     em_d
7402   ambos
3048   ambos
6860   ambos
7461   ambos
9217   ambos
6534   ambos
2936   ambos
10290   em_o
10832  ambos
4563    em_o
1504   ambos
6465   ambos
9845   ambos
9626   ambos
7129   ambos
10452  ambos
8562   ambos
4254   ambos
7578   ambos
1182   ambos
9618   ambos
9492   ambos
529    ambos
6639    em_d
10167  ambos
8336   ambos

In [457]:
datos_mx.to_csv(DATOS / "procesados" / "datos_analizados_solomx.csv", index=False)